image: python:3.11-bookworm
pipelines:
  default:
    - step:
        caches:
          - poetry
        services:
          - selenium
        script:
          - curl -sSL https://install.python-poetry.org | python3
          - PATH=$PATH:$HOME/.local/bin
          - poetry config virtualenvs.create false
          - poetry install --no-root
          - poetry run behave --junit --junit-directory "test-reports" -D INTEGRATION_TEST_USER_1_PWD=$INTEGRATION_TEST_USER_1_PWD
        artifacts:
          - test-reports/*.xml
definitions:
  caches:
    poetry: ~/.cache/pypoetry
  services:
    selenium:
      image: selenium/standalone-firefox:114.0
